---
name: update-default-pr-template
on:
  push:
jobs:
  updater:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: |
          THE_FILE=.github/pull_request_template.md
          echo "Please go to the \`Preview\` tab and select the appropriate sub-template:\n" > $THE_FILE
          file_list=$(ls -1 .github/PULL_REQUEST_TEMPLATE/*.md)
          for i in "${file_list}"
          do
            echo $i
            TEMPLATE_i=$(basename $i)
            echo "\* [${TEMPLATE_i}](?expand=1&template=${i})" >> $THE_FILE
          done
          cat $THE_FILE
      # TODO commit to repo
